### ISSUE TITLE
Bump object_store to 0.13.1

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#1140]
`object_store` 0.13.0 was just released:

https://github.com/apache/arrow-rs-object-store/issues/367

There's no pressing need, but we might want to consider upgrading to it (even if #1104 is implemented quickly, I think we will still have object_store floating around for a while). I took a brief look and it seems the core `ObjectStore` trait has changed a bit (there's now an `ObjectStoreExt` with sync functions that return a Future). It took more than a minute to upgrade, so I backed off.

**Comment by criccomini** [comment]
Looks like object_store_opendal is still using 0.12.3:

https://github.com/apache/opendal/blob/dd67846f2d26d9c84d6154ce57e58dfe6825d116/integrations/object_store/Cargo.toml#L45

We'll need them to go to 0.13 before we can upgrade.

**Comment by criccomini** [comment]
This prompted worked quite well in the SlateDB codebase with Codex 5.2 xhigh:

```
I've updated Cargo.toml to use 0.13.1 for object_store (previously, we were on 0.12.3). The code no longer builds. Fix the code so it works with 0.13.1 now. Here are some tips from the object_store codebase:

/// # Upgrade Guide for 0.13.0
///
/// Upgrading to object_store 0.13.0 from an earlier version typically involves:
///
/// 1. Add a `use` for [`ObjectStoreExt`] to solve the error
///
/// ```text
/// error[E0599]: no method named `put` found for reference `&dyn object_store::ObjectStore` in the current scope
///    --> datafusion/datasource/src/url.rs:993:14
/// ```
///
/// 2. Remove any (now) redundant implementations (such as `ObjectStore::put`) from any
///   `ObjectStore` implementations to resolve the error
///
/// ```text
/// error[E0407]: method `put` is not a member of trait `ObjectStore`
///     --> datafusion/datasource/src/url.rs:1103:9
///      |
/// ```
///
/// 3. Convert `ObjectStore::delete` to [`ObjectStore::delete_stream`] (see documentation
///    on that method for details and examples)
///
/// 4. Combine `ObjectStore::copy` and `ObjectStore::copy_if_not_exists` implementations into
///    [`ObjectStore::copy_opts`] (see documentation on that method for details and examples)
///
/// 5. Update `object_store::Error::NotImplemented` to include the name of the missing method
///
/// For example, change instances of
/// ```text
/// object_store::Error::NotImplemented
/// ```
/// to
/// ```
/// object_store::Error::NotImplemented {
///    operation: "put".to_string(),
///    implementer: "RequestCountingObjectStore".to_string(),
///  };
/// ```
///
```

**Comment by criccomini** [comment]
OpenDAL just bumped to 0.13.1 last week:

https://github.com/apache/opendal/commit/173feb6d22a35d176e354bd5e20e2802dc28b93f
